--------------------------------------------------------
--  Mock legacy AP invoice data for the Invoice History
--  demo page.  Two source systems:
--    Legacy  – older ERP (pre-2020 data)
--    EBS     – Oracle E-Business Suite (2018-2022)
--
--  Supplier: Lee Supplies (matches PO demo data)
--  Business Unit: Sierra-Cedar US BU (matches Fusion)
--------------------------------------------------------

truncate table demo_ap_invoices_hist;

------------------------------------------------------------------------
-- Legacy source  (2015-2020)
------------------------------------------------------------------------
insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500001, 'INF-2015-0001', 'USD', 'USD', 12500.00, date '2015-03-15', date '2015-03-15', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Classroom textbooks - Spring 2015', 'LPO-2015-0001', timestamp '2015-03-14 10:30:00', 'jane.smith@legacy.local', timestamp '2015-04-20 14:00:00', 'jane.smith@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500002, 'INF-2015-0002', 'USD', 'USD', 8750.00, date '2015-07-01', date '2015-07-01', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'IT equipment - Summer refresh', 'LPO-2015-0002', timestamp '2015-06-28 09:15:00', 'jane.smith@legacy.local', timestamp '2015-08-05 11:00:00', 'jane.smith@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500003, 'INF-2016-0001', 'USD', 'USD', 45000.00, date '2016-02-01', date '2016-02-01', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 45', 'External', 'HVAC maintenance contract FY16', 'LPO-2016-0001', timestamp '2016-01-28 08:45:00', 'bob.johnson@legacy.local', timestamp '2016-03-15 16:30:00', 'bob.johnson@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500004, 'INF-2016-0002', 'USD', 'USD', 3200.00, date '2016-04-15', date '2016-04-15', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Office supplies Q2 2016', 'LPO-2016-0002', timestamp '2016-04-12 13:00:00', 'jane.smith@legacy.local', timestamp '2016-05-18 10:00:00', 'jane.smith@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500005, 'INF-2017-0001', 'USD', 'USD', 67500.00, date '2017-03-01', date '2017-03-01', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 60', 'External', 'Student laptops - 1:1 initiative Phase 1', 'LPO-2017-0001', timestamp '2017-02-25 11:00:00', 'bob.johnson@legacy.local', timestamp '2017-05-01 09:30:00', 'bob.johnson@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500006, 'INF-2017-0002', 'USD', 'USD', 15800.00, date '2017-08-10', date '2017-08-10', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Cafeteria equipment replacement', null, timestamp '2017-08-05 14:20:00', 'jane.smith@legacy.local', timestamp '2017-09-12 11:45:00', 'jane.smith@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500007, 'INF-2018-0001', 'USD', 'USD', 22000.00, date '2018-01-20', date '2018-01-20', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Classroom furniture - new wing', 'LPO-2018-0001', timestamp '2018-01-15 09:00:00', 'bob.johnson@legacy.local', timestamp '2018-02-22 15:30:00', 'bob.johnson@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500008, 'INF-2018-0002', 'USD', 'USD', 9400.00, date '2018-06-01', date '2018-06-01', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Science lab supplies FY18', null, timestamp '2018-05-28 10:30:00', 'jane.smith@legacy.local', timestamp '2018-07-05 13:00:00', 'jane.smith@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500009, 'INF-2019-0001', 'USD', 'USD', 38000.00, date '2019-03-10', date '2019-03-10', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 45', 'External', 'Bus fleet maintenance parts', 'LPO-2019-0001', timestamp '2019-03-05 08:00:00', 'bob.johnson@legacy.local', timestamp '2019-04-25 10:15:00', 'bob.johnson@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500010, 'INF-2019-0002', 'USD', 'USD', 5600.00, date '2019-09-15', date '2019-09-15', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Athletic equipment - Fall sports', null, timestamp '2019-09-12 11:00:00', 'jane.smith@legacy.local', timestamp '2019-10-20 14:30:00', 'jane.smith@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500011, 'INF-2020-0001', 'USD', 'USD', 82000.00, date '2020-02-01', date '2020-02-01', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 60', 'External', 'Student laptops - 1:1 initiative Phase 2', 'LPO-2020-0001', timestamp '2020-01-25 09:45:00', 'bob.johnson@legacy.local', timestamp '2020-04-10 16:00:00', 'bob.johnson@legacy.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('Legacy', 500012, 'INF-2020-0002', 'USD', 'USD', 14200.00, date '2020-06-15', date '2020-06-15', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'PPE and sanitization supplies - COVID', null, timestamp '2020-06-10 08:30:00', 'jane.smith@legacy.local', timestamp '2020-07-18 12:00:00', 'jane.smith@legacy.local');

------------------------------------------------------------------------
-- EBS source  (2018-2022)
------------------------------------------------------------------------
insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600001, 'LAW-40001', 'USD', 'USD', 18500.00, date '2018-02-20', date '2018-02-20', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Network switches - district-wide upgrade', 'EBS-40001', timestamp '2018-02-18 10:00:00', 'mary.williams@ebs.local', timestamp '2018-03-25 14:30:00', 'mary.williams@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600002, 'LAW-40002', 'USD', 'USD', 6300.00, date '2018-07-25', date '2018-07-25', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Janitorial supplies Q3 2018', null, timestamp '2018-07-22 09:30:00', 'mary.williams@ebs.local', timestamp '2018-08-28 11:00:00', 'mary.williams@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600003, 'LAW-40003', 'USD', 'USD', 52000.00, date '2019-01-15', date '2019-01-15', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 45', 'External', 'Modular classroom building', 'EBS-40003', timestamp '2019-01-10 08:00:00', 'tom.davis@ebs.local', timestamp '2019-03-01 16:45:00', 'tom.davis@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600004, 'LAW-40004', 'USD', 'USD', 4100.00, date '2019-06-01', date '2019-06-01', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Printer toner and paper - bulk', null, timestamp '2019-05-28 13:15:00', 'mary.williams@ebs.local', timestamp '2019-07-02 10:30:00', 'mary.williams@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600005, 'LAW-40005', 'USD', 'USD', 27500.00, date '2019-11-20', date '2019-11-20', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Security camera system - Phase 1', 'EBS-40005', timestamp '2019-11-15 10:00:00', 'tom.davis@ebs.local', timestamp '2019-12-22 15:00:00', 'tom.davis@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600006, 'LAW-40006', 'USD', 'USD', 11200.00, date '2020-03-25', date '2020-03-25', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Remote learning hotspots - COVID response', null, timestamp '2020-03-20 08:45:00', 'mary.williams@ebs.local', timestamp '2020-04-28 14:00:00', 'mary.williams@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600007, 'LAW-40007', 'USD', 'USD', 33000.00, date '2020-08-15', date '2020-08-15', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 45', 'External', 'HVAC air filtration upgrades', 'EBS-40007', timestamp '2020-08-10 11:30:00', 'tom.davis@ebs.local', timestamp '2020-10-01 09:00:00', 'tom.davis@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600008, 'LAW-40008', 'USD', 'USD', 7800.00, date '2021-02-10', date '2021-02-10', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Cafeteria disposables - COVID protocols', null, timestamp '2021-02-05 09:00:00', 'mary.williams@ebs.local', timestamp '2021-03-15 13:30:00', 'mary.williams@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600009, 'LAW-40009', 'USD', 'USD', 41000.00, date '2021-07-20', date '2021-07-20', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 60', 'External', 'Chromebook fleet replacement', 'EBS-40009', timestamp '2021-07-15 10:00:00', 'tom.davis@ebs.local', timestamp '2021-09-30 16:00:00', 'tom.davis@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600010, 'LAW-40010', 'USD', 'USD', 16500.00, date '2022-01-25', date '2022-01-25', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Playground equipment - ADA compliance', null, timestamp '2022-01-20 08:30:00', 'mary.williams@ebs.local', timestamp '2022-03-01 11:00:00', 'mary.williams@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600011, 'LAW-40011', 'USD', 'USD', 9200.00, date '2022-07-05', date '2022-07-05', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 30', 'External', 'Library books and media - FY22', null, timestamp '2022-07-01 14:00:00', 'tom.davis@ebs.local', timestamp '2022-08-08 10:30:00', 'tom.davis@ebs.local');

insert into demo_ap_invoices_hist (sourcesystem, invoiceid, invoicenumber, invoicecurrency, paymentcurrency, invoiceamount, invoicedate, accountingdate, businessunit, supplier, suppliernumber, suppliersite, validationstatus, approvalstatus, paidstatus, accountingstatus, invoicetype, paymentterms, invoicesource, description, purchaseordernumber, creationdate, createdby, lastupdatedate, lastupdatedby)
values ('EBS', 600012, 'LAW-40012', 'USD', 'USD', 24000.00, date '2022-10-10', date '2022-10-10', 'Sierra-Cedar US BU', 'Lee Supplies', '2001', 'US Site', 'Validated', 'Workflow approved', 'Paid', 'Accounted', 'Standard', 'Net 45', 'External', 'Security camera system - Phase 2', 'EBS-40012', timestamp '2022-10-05 09:00:00', 'mary.williams@ebs.local', timestamp '2022-11-15 15:45:00', 'mary.williams@ebs.local');

commit;

-- verify
select sourcesystem, count(*) as inv_count, to_char(sum(invoiceamount), 'FM$999,999,990.00') as total_value
from demo_ap_invoices_hist
group by sourcesystem
order by sourcesystem;
/
